version: '2'
services:
  database:
    image: postgres
    volumes:
      - ./data/pgdata:/pgdata
    env_file:
      - '.env'
  web:
    image: yara
    links:
      - database
    build: .
    volumes:
      - .:/opt/yetanotherrailsapp
    ports:
      - '9292:9292'
    command: [bundle, exec, puma]
    env_file:
      - '.env'
volumes:
  yara-sync:
    external: true
