
version: '2'
services:
  database:
    image: postgres
    env_file:
      - '.env'
  web:
    image: yara
    links:
      - database
      - redis
    build: .
    ports:
      - '80:9292'
    command: [bundle, exec, puma]
    env_file:
      - '.env'
  redis:
    image: 'redis:3.2-alpine'
    command: [redis-server]
    ports:
      - '6379:6379'
  sidekiq:
    image: yara
    links:
      - database
      - redis:foo.redis.server
    build: .
    command: [bundle, exec, sidekiq]
    env_file:
      - '.env'
