default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: database
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: yetanotherrailsapp_development
